version: "3.9"

services:
  db:
    image: postgres:16
    container_name: team-db
    environment:
      POSTGRES_DB: team
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d team"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - team-net

  minio:
    image: minio/minio:latest
    container_name: team-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio1234
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Веб-консоль
    volumes:
      - ./minio-data:/data
    networks:
      - team-net

  app:
    build: .
    container_name: team-app
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/team
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SERVER_PORT: 8500

      # MinIO интеграция (на будущее)
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minio1234
    ports:
      - "8500:8500"
    networks:
      - team-net

networks:
  team-net:
    driver: bridge
